version: "3.8"
services:
  frontend:
    container_name: FrontContainer
    build:
      context: ./vite-project  # Asegúrate de que esta ruta sea correcta
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Monta tu archivo de configuración
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    container_name: BackContainer
    build:
      context: ./backend  # Ruta al código fuente del backend
      dockerfile: Dockerfile  # Nombre del Dockerfile en la carpeta del backend
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=Prestabanco
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    container_name: payroll-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Prestabanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
